title:            紅一葉
description:
url:              http://miao.hu/
signoff:          Maple
disqus_shortname: "maple"
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: "UA-40449098-1"

links:
  - name:         Blog
    url:          /
  - name:         RSS
    url:          /atom.xml
  - name:         GitHub
    url:          http://github.com/humiaozuzu
    external:     true
  - name:         About
    url:          /about.html
highlighter:      pygments
permalink:        /:year/:month/:day/:title
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
